### PR TITLE
ref:replace underscore with lodash.uniq to reduce bundle size

### PR DESCRIPTION
**Pull request by anshulsahni**
After we started pushing compiled version of the action, I had a look over the build size we were using underscore for just one function which is `_.uniq`. Replaced it with `lodash.uniq` and bundle size came down from `129KB` to `110KB`, might not be a big win from size perspective but it still a reduction of `14%` 😎 

_Below 👇🏼 are some of the comparison of bundle size with different schemes of underscore and lodash_

**With underscore** _(current)_
_Bundle size: 129 KB_
image

**With lodash** _(importing as lodash/uniq)_
_Bundle size: 113KB_
image

**With lodash.uniq** _(finalized in this PR)_
_Bundle Size: 110KB_
image

### CODE REVIEW

**Comment by anshulsahni** [comment]
@adamzolyak Please have look on this

**Comment by anshulsahni** [comment]
@adamzolyak you got chance to have a look on this?

**Comment by adamzolyak** [comment]
I’ll look tomorrow. Sorry I was away this week. I need a GitHub out of office 😁. 

-Adam

**Comment by anshulsahni** [comment]
No issues @adamzolyak, thanks for response 🙂

**Review by adamzolyak — APPROVED** [review]
Looks good. Thanks for the contribution! Can you release it - do you have permissions?

**Comment by anshulsahni** [comment]
@adamzolyak will check today whether or not I have permission to release or not

**Pull request merged**
