### PR TITLE
Chore: Provide compiled version to improve CI time

### PR DESCRIPTION
**Pull request by Jarrku**
Provides a compiled version of the package, and directly run it using node.

Decreased the CI time of the action from 42s to 3s in our repo:

Old:
image

New:
image

### CODE REVIEW

**Comment by adamzolyak** [comment]
@Jarrku looks good to me! Thanks for your contribution. @anshulsahni thoughts? Good to merge?

**Comment by Jarrku** [comment]
Note: This required you to run `npm run build` & push the output as well before doing releases. Maybe a pre-commit/CI check would be helpful to validate this, but thought that was out of scope of this PR.

**Comment by anshulsahni** [comment]
@Jarrku is there a way we can avoid committing `dist/` folder?

**Comment by Jarrku** [comment]
No, it's actually a requirement, and recommended by the Github Actions docs:
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

By providing the compiled `dist` code, consumers dont have to build the action themselves on every run.

**Comment by anshulsahni** [comment]
@Jarrku @adamzolyak Sorry for the delay stuck in some P0 issue, will close this today

_PS: my local timezone is IST_

**Comment by Jarrku** [comment]
No worries, currently using my fork anyway :)

**Review by adamzolyak — CHANGES_REQUESTED** [review]
@Jarrku could you add a releasing section to Contributing.md with the updated release instructions now that there are a few steps? Other than that, I think this is good to go.

**Comment by Jarrku** [comment]
@adamzolyak  Updated the CONTRIBUTING file. Is it clear enough?

**Review by adamzolyak — APPROVED** [review]

**Comment by adamzolyak** [comment]
Thanks again @Jarrku! 🙌

Released as https://github.com/TinkurLab/monorepo-pr-labeler-action/releases/tag/3.1.0

**Pull request merged**
